export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_NEWS_BY_CATEGORY = 'FETCH_NEWS_BY_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const SELECT_NEWS_ITEM = 'SELECT_NEWS_ITEM';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';
